blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.views import *

urlpatterns = [
   url(r'^$', PostLV.as_view(), name='index'),
   url(r'^post/(?P<slug>\w+)/$', PostDV.as_view(), name='post_detail'),
  # url(r'^post/(?P<slug>\w+)/comment/$', add_comment_to_post, name='add_comment_to_post'),
]

my_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from my_blog.views import HomeView, Introduce


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^introduce/$', Introduce, name = 'introduce'),
]

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
from tagging.fields import *
from ckeditor.fields import RichTextField


class Post(models.Model):

    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    content = RichTextField('CONTENT')
    create_date =models.DateTimeField('Create Date', auto_now_add = True)
    modify_date = models.DateTimeField('Modify Date', auto_now = True)
    tag =TagField()

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'my_post'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()


"""
class Comment(models.Model):
    post = models.ForeignKey('Post', related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    password = models.CharField(max_length=50)
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)


    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'
        db_table = 'my_comment'

    def __str__(self):
        return self.text

    def get_absolute_url(self):
       return reverse('blog:add_comment_to_post', args=(self.slug,))
"""

blog/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from tagging.models import Tag, TaggedItem
from tagging.views import TaggedObjectList
#rom django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from blog.models import Post#, Comment
from django.shortcuts import render, redirect
#from blog.form import CommentForm

class PostLV(ListView) :
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 10


class PostDV(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

"""
    def add_comment_to_post(request, slug):
        post = get_object_or_404(Post, slug=slug)
        if request.method == "POST":
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.post = post
                comment.save()
            return redirect('blog:post_detail', slug=post.slug)
        else:
            form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

    class admin:
      pass
"""

my_blog/views.py
from django.views.generic import ListView, DetailView


from blog.models import Post
from django.shortcuts import render, redirect
#from blog.form import CommentForm
from blog.models import Post

class HomeView(ListView):
    template_name = 'home.html'
    model = Post
    context_object_name = 'posts'
    paginate_by = 4

def Introduce(request):
   return render(request, 'introduce.html')

blog/templates/blog/add_comment_to_post.html
{% extends "base.html" %}

{% block title %}GLAY's blog{% endblock %}

{% block content %}
<div id="content">
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
</div>
{% endblock %}

blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %}GLAY's blog{% endblock %}

{% block content %}
<div id="content">
    <h1>Post List</h1>

    {% for post in posts %}
        <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
        {{ post.modify_date|date:"N d, Y" }}
        <a href='{{ post.get_absolute_url }}'>Comments: {{ post.approved_comments.count }}</a>
    {% endfor %}

    <br/>
<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
        {% endif %}
    </span>

</div>

</div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; JJS 2016
</div>
{% endblock footer %}

blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}

{% block content %}
<div id="content">

<h1>Post Archives until {% now "N d, Y" %}</h1>
<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year-{{ date|date:"Y" }}</a></li>
    {% endfor %}
</ul>
<br/>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}post_archive_day.html{% endblock %}

{% block content %}
<div id="content">

<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}post_archive_month.html{% endblock %}

{% block content %}
<div id="content">

<h1>Post Archives for {{ month|date:"N, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}post_archive_year.html{% endblock %}

{% block content %}
<div id="content">

<h1>Post Archives for {{ year|date:"Y" }}</h1>

<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F" }}</a></li>
    {% endfor %}
</ul>
<br/>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}post_detail.html{% endblock %}

{% block content %}
<div id="content">

<h2>{{ object.title }}</h2>

<p class="other_posts">
    {% if object.get_previous_by_modify_date %}
    <a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous post">&laquo;--{{ object.get_previous_post }}</a>
    {% endif %}

    {% if object.get_next_by_modify_date %}
    | <a href="{{ object.get_next_post.get_absolute_url }}" title="View next post">{{ object.get_next_post }}--&raquo;</a>
    {% endif %}
</p>

<p class="date">{{ object.modify_date|date:"j F Y" }}</p>
<br/>

<div class="body">
    {{ object.content|linebreaks }}
</div>


<div>
    {% load disqus_tags %}
    {% disqus_show_comments %}
</div>


</div>
{% endblock content%}

blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block title %}post_Search.html{% endblock %}

{% block content %}
<div id ="content">
    <h1>Blog Search</h1>
    <from action = "." method ="post"> {% csrf_token %}
    {{ form.as_table}}
    <input type=""submit" value="Submit"/>
    </from>

<br/><br/>

    {% if object_list %}
    {% for post in object_list %}
    <h2><a href = '{{post.get_absolute_url}}'>{{post.title}}</a></h2>
    {{post.modify_date|date:"N d, Y"}}
    <p>{{post.description}}</p>

    {% endfor %}

    {% elif search_term %}
    <b><i>Search Word({{ search_term }}) Not Found ! </i></b>
    {% endif %}

</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
<title>{% block title %}Second life{% endblock %}</title>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>
 <div id="top">
     <h1 class="title">Second life's Blog</h1>
     <li class="menu"><a href="{% url 'home' %}">Home</a></li>
     <li class="menu"><a href="{% url 'introduce' %}">Introduce</a></li>
     <li class="menu"><a href="{% url 'blog:index' %}">Blog</a></li>
 </div>

{% block content %}{% endblock %}

{% block footer %}{% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Second life Home{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}

<div id="post_latest">
    <h1>The latest List</h1>
    {% for post in posts %}
    <a class="post" href='{{ post.get_absolute_url }}'>{{ post.title }}</a>
    {{ post.modify_date|date:"N d, Y" }}
    <br/>
    {% endfor %}
</div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; Second life 2016
</div>
{% endblock footer %}

templates/introduce.html
{% extends "base.html" %}

{% block title %}Second life's Introduce{% endblock %}

{% block content %}

<div id="content">
    <h2 style="bold">Who we are?</h2>
    <p>
        안녕하세요.
        Second life입니다.
        두 명의 개발자로 이루어져 있으며,
        J군은 Second life의 기획 및 개발 총괄,
        K군은 개발을 담당하고 있습니다.
    </p>
    <h2 style="bold">Why is second life?</h2>
    <p>
        직장이든 어떤 한 일을 하시고 계시든 간에 인생에서 한 번은 창업은 하게 될 것이고
        창업은 당신의 인생을 좀 더 나은 삶으로 이끌 수 있을 것입니다.
        창업은 당신의 새로운 출발, 즉 Second life로 이어질 것입니다.
        그렇기에 Second life는 혼자서도 아이디어를 어떻게 다듬고 기획하여 구체화 시키는 과정에 도움이 되고자 합니다.
    </p>
</div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; Second life 2016
</div>
{% endblock footer %}

templates/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div class="VirtualView">
	<div class="hideMenuBody" id="hideMenuBodyId">
		<div>Menu 1</div>
		<div>Menu 2</div>
		<div>Menu 3</div>
		<div>Menu 4</div>
		<div>Menu 5</div>
		<div onclick="closeLeftMenu(); return false;">Close</div>
	</div>

	<div class="circleBt" id="circleBt" onclick="showLeftMenu(this); return false;">
		<div style="margin-top: 13px;"></div>
		<div></div>
		<div></div>
	</div>


</div>
</body>
</html>